<?php
/**
 * @file
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function mcrc_password_reset_form_alter(&$form, &$form_state, $form_id) {

  if (in_array($form_id, array('user_register_form', 'user_login'))) {
    $form['mcrc_password_reset'] = array(
      '#markup' => '<div class="alert alert-info"><i class="icon-info-sign"></i> ' . t('Please note that if you had an account on the old website, it still exists, although you must reset your password by using the !reset_pwd.  After resetting, you will receive an email with instructions on what to do next.', array('!reset_pwd' => l('<em>' . t('reset password page') . '</em>', 'user/password', array('html' => TRUE)))) . '</div>',
      '#weight' => -10,
    );
  }
}
